require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ChecksController do

  def mock_check(stubs={})
    @mock_check ||= mock_model(Check, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all checks as @checks" do
      Check.stub(:all) { [mock_check] }
      get :index
      assigns(:checks).should eq([mock_check])
    end
  end

  describe "GET show" do
    it "assigns the requested check as @check" do
      Check.stub(:find).with("37") { mock_check }
      get :show, :id => "37"
      assigns(:check).should be(mock_check)
    end
  end

  describe "GET new" do
    it "assigns a new check as @check" do
      Check.stub(:new) { mock_check }
      get :new
      assigns(:check).should be(mock_check)
    end
  end

  describe "GET edit" do
    it "assigns the requested check as @check" do
      Check.stub(:find).with("37") { mock_check }
      get :edit, :id => "37"
      assigns(:check).should be(mock_check)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created check as @check" do
        Check.stub(:new).with({'these' => 'params'}) { mock_check(:save => true) }
        post :create, :check => {'these' => 'params'}
        assigns(:check).should be(mock_check)
      end

      it "redirects to the created check" do
        Check.stub(:new) { mock_check(:save => true) }
        post :create, :check => {}
        response.should redirect_to(check_url(mock_check))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved check as @check" do
        Check.stub(:new).with({'these' => 'params'}) { mock_check(:save => false) }
        post :create, :check => {'these' => 'params'}
        assigns(:check).should be(mock_check)
      end

      it "re-renders the 'new' template" do
        Check.stub(:new) { mock_check(:save => false) }
        post :create, :check => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested check" do
        Check.stub(:find).with("37") { mock_check }
        mock_check.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :check => {'these' => 'params'}
      end

      it "assigns the requested check as @check" do
        Check.stub(:find) { mock_check(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:check).should be(mock_check)
      end

      it "redirects to the check" do
        Check.stub(:find) { mock_check(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(check_url(mock_check))
      end
    end

    describe "with invalid params" do
      it "assigns the check as @check" do
        Check.stub(:find) { mock_check(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:check).should be(mock_check)
      end

      it "re-renders the 'edit' template" do
        Check.stub(:find) { mock_check(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested check" do
      Check.stub(:find).with("37") { mock_check }
      mock_check.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the checks list" do
      Check.stub(:find) { mock_check }
      delete :destroy, :id => "1"
      response.should redirect_to(checks_url)
    end
  end

end
