require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CountersController do

  def mock_counter(stubs={})
    @mock_counter ||= mock_model(Counter, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all counters as @counters" do
      Counter.stub(:all) { [mock_counter] }
      get :index
      assigns(:counters).should eq([mock_counter])
    end
  end

  describe "GET show" do
    it "assigns the requested counter as @counter" do
      Counter.stub(:find).with("37") { mock_counter }
      get :show, :id => "37"
      assigns(:counter).should be(mock_counter)
    end
  end

  describe "GET new" do
    it "assigns a new counter as @counter" do
      Counter.stub(:new) { mock_counter }
      get :new
      assigns(:counter).should be(mock_counter)
    end
  end

  describe "GET edit" do
    it "assigns the requested counter as @counter" do
      Counter.stub(:find).with("37") { mock_counter }
      get :edit, :id => "37"
      assigns(:counter).should be(mock_counter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created counter as @counter" do
        Counter.stub(:new).with({'these' => 'params'}) { mock_counter(:save => true) }
        post :create, :counter => {'these' => 'params'}
        assigns(:counter).should be(mock_counter)
      end

      it "redirects to the created counter" do
        Counter.stub(:new) { mock_counter(:save => true) }
        post :create, :counter => {}
        response.should redirect_to(counter_url(mock_counter))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved counter as @counter" do
        Counter.stub(:new).with({'these' => 'params'}) { mock_counter(:save => false) }
        post :create, :counter => {'these' => 'params'}
        assigns(:counter).should be(mock_counter)
      end

      it "re-renders the 'new' template" do
        Counter.stub(:new) { mock_counter(:save => false) }
        post :create, :counter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested counter" do
        Counter.stub(:find).with("37") { mock_counter }
        mock_counter.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :counter => {'these' => 'params'}
      end

      it "assigns the requested counter as @counter" do
        Counter.stub(:find) { mock_counter(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:counter).should be(mock_counter)
      end

      it "redirects to the counter" do
        Counter.stub(:find) { mock_counter(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(counter_url(mock_counter))
      end
    end

    describe "with invalid params" do
      it "assigns the counter as @counter" do
        Counter.stub(:find) { mock_counter(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:counter).should be(mock_counter)
      end

      it "re-renders the 'edit' template" do
        Counter.stub(:find) { mock_counter(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested counter" do
      Counter.stub(:find).with("37") { mock_counter }
      mock_counter.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the counters list" do
      Counter.stub(:find) { mock_counter }
      delete :destroy, :id => "1"
      response.should redirect_to(counters_url)
    end
  end

end
